### ISSUE TITLE
Design home page CSS

### ISSUE THREAD

**Issue by AlbinoDrake238** [EECE3093C/team-project-jam-frontend#20]
Implement the home page CSS so we have a consistent style throughout our program.
Requirements:
- CSS looks nice and the flow of the webpage is easy to follow.

**Comment by ItsAtlasX** [comment]
working on this

**Comment by ItsAtlasX** [comment]
progress has made, need to fix chosen spotify logo png, current one has white background in the image. need to fix some text box formatting and color settings still.
