### ISSUE TITLE
Familiarize yourself with next.js

### ISSUE THREAD

**Issue by AlbinoDrake238** [EECE3093C/team-project-jam-frontend#21]
next.js is a react based framework, and is the most recommended react framework from the react website. Should set aside 2-3hrs in order to familiarize yourself with the framework.

**Comment by ItsAtlasX** [comment]
I will look at that today

**Comment by AlbinoDrake238** [comment]
Here are some resources I've been looking at concerning outing:
- https://nextjs.org/docs/routing/introduction
- https://nextjs.org/docs/api-reference/next/link
- https://nextjs.org/docs/api-reference/next/router

**Comment by ItsAtlasX** [comment]
I am confident in this now
